cdp/wallet.py

- Allow `wallet.save_seed("seeds.json")` to create a new file if one doesn't already exist.

[chore] Allow wallet.save_seed to create a file if necessary

---

Makefile
cdp/__init__.py
cdp/wallet.py
cdp/wallet_data.py
docs/cdp.rst

- import and export `WalletData` so that user's can store 1-1 wallet data in locations other than local file
- Force update doc generation files when calling `make docs`

[chore] Import/Export WalletData

---

cdp/trade.py
tests/test_trade.py

- Add `status` property to the `Trade` class + update tests

[chore] Add status Property to Trade

---

CHANGELOG.md
cdp/wallet.py
tests/test_wallet.py

- Fix bug that caused an exception to be raised when getting `wallet.default_address` directly after `wallet.load_seed(...)`

[chore] Fix Get Default Address on Newly Hydrated Wallet

---

.github/workflows/publish_docs.yml
Makefile

- Generate `cdp` docs for new modules via `make docs` during publish docs GHA workflow
- Add `make local-docs` command to run the docs site locally

[chore] Fully Automate Doc Generation via GHA

---

CHANGELOG.md
cdp/__init__.py
cdp/payload_signature.py
cdp/wallet.py
cdp/wallet_address.py
tests/test_payload_signature.py
tests/test_wallet.py
tests/test_wallet_address.py

- Arbitrary message signing support via `wallet.sign_payload(...)`
- Following up with helpers to hash EIP-191 and EIP-712 data messages!

[PSDK-499] Payload Signature Support

---

cdp/wallet_address.py
tests/test_wallet_address.py

The user should be able to transfer the entire balance from their account.

fix:  transfer amount less than or equal to the balance.

---

cdp/cdp.py
cdp/cdp_api_client.py
cdp/constants.py
tests/test_api_client.py

This PR does the following: 
1. Adds `source` and `source_version` to the `Cdp` and `CdpApiClient` to be able to differentiate between pure sdk usage and Agentkit extensions. 
2. Tracks this information in string returned by the `_get_correlation_data` method for `CdpApiClient` by adding `source=sdk `and `source_version=__version__`
3. Adds a unit test for the above method.
If there was an error, `_get_correlation_data` would not work, but this method is tested. To fix the error, we should rollback.

Adds source and source type for better usage monitoring

---

CHANGELOG.md
cdp/asset.py
tests/test_asset.py
tests/test_balance.py

- Right now, we use the passed in asset_id to set the decimals correctly. We don't however set the asset_id. Ruby SDK does this correctly:
```
new(
network: Coinbase.to_sym(asset_model.network_id),
asset_id: asset_id || Coinbase.to_sym(asset_model.asset_id),
address_id: asset_model.contract_address,
decimals: decimals
)
```
Updated unit tests to assert the asset ID in test_asset.py, which confirmed the bug. Tests now pass. Had to also update test_balance.py which actually asserted that the asset_id stored on a balance was different than the model asset, which was wrong.

Fix Asset from_model bug to use passed in asset_id when initializing

---

cdp/wallet_address.py
tests/test_wallet_address.py

feat: export wallet address

---

cdp/wallet_address.py
tests/test_wallet_address.py

- Forgot to merge this in my earlier PR, this fixes quote to correctly use the normalized decimal amount

Fix quote fund to properly pass in normalized amount

---

.github/workflows/publish.yml
.github/workflows/publish_docs.yml

- Trigger PyPI release on tag release
- Use poetry virtualenv for GHA to build docs

fix: Use Poetry Virtualenv during Docs Build GHA

---

CHANGELOG.md
README.md
cdp/wallet.py
cdp/wallet_data.py
tests/test_wallet.py

It should be clear which saved wallets belong to which networks when you `save_seed` / `export_data` for a given wallet.
After running:
```python
wallet = Wallet.create(network_id="base-mainnet")
print(wallet.export_data())
wallet.save_seed("/Users/ryan/code/public/seeds/wallet_seed.json")
```
`wallet_seed.json` looks like:
```json
{
"11cd62ab-0046-472d-bb16-3ad560bdf2d4": {
"seed": "21exxx",
"encrypted": false,
"auth_tag": "",
"iv": "",
"network_id": "base-mainnet"
}
}
```
And the result of `wallet.export()`:
```
WalletData: (wallet_id: 11cd62ab-0046-472d-bb16-3ad560bdf2d4, seed: 21exxx, network_id: base-mainnet)
```
The network id should always be present, and if it is not, it will simply not be included in the WalletData

chore(PSDK-640): add network_id to WalletData

---

CHANGELOG.md
cdp/smart_contract.py
tests/test_smart_contract.py

Change update api from classmethod to instance method
```
>>> sc = SmartContract.register(contract_name="Test Contract", contract_address="0x0000000071727de22e5e9d8baf0edac6f37da039", network_id="base-sepolia", abi=[
...   {
...     "constant": True,
...     "name": "myField",
...     "outputs": [
...       {
...         "name": "",
...         "type": "uint256"
...       }
...     ],
...     "type": "function"
...   }
... ])
CDP API REQUEST: POST https://cloud-api-dev.cbhq.net/platform/v1/networks/base-sepolia/smart_contracts/0x0000000071727de22e5e9d8baf0edac6f37da039/register
CDP API RESPONSE: Status: 200, Data: b'{"abi":"[{\\"constant\\":true,\\"name\\":\\"myField\\",\\"outputs\\":[{\\"name\\":\\"\\",\\"type\\":\\"uint256\\"}],\\"type\\":\\"function\\"}]","contract_address":"0x000000007 …
```

feat: Change update api to be an instance method

---

CHANGELOG.md
cdp/__init__.py
cdp/cdp_api_client.py
cdp/mnemonic_seed_phrase.py
cdp/wallet.py
cdp/wallet_data.py
pyproject.toml
tests/test_wallet.py

- Support external 1-of-1 wallet import via BIP-39 mnemonic phrases (12, 15, 18, 21, or 24 words)
- Support import of wallet data exported from CDP Python SDK
- Deprecate `Wallet.load_seed` method in favor of `Wallet.load_seed_from_file`
- Deprecate `Wallet.save_seed` method in favor of `Wallet.save_seed_to_file`
Tested via:
- Import of 12, 15, 18, 21, and 24-word mnemonic seed phrases
- Export of wallets generated via mnemonic seed phrases
- Import of wallets generated via mnemonic seed phrases, that were then exported
- Successfully imported wallet exported from CDP NodeJS SDK `v0.11.0`

feat(PSDK-670): Support external wallet imports, wallet imports from CDP Python SDK

---

CHANGELOG.md
cdp/webhook.py
tests/test_webhook.py

make python SDK's webhook deletion behave the same as node and ruby SDK, it will be a instance method without needing clients to enter a webhook ID. 
```
wh1 = next(gen1)
CDP API REQUEST: GET https://api.cdp.coinbase.com/platform/v1/webhooks?limit=100
CDP API RESPONSE: Status: 200, Data: b'{"data":[{"created_at":"2024-12-13T20:24:39.256Z","event_type":"smart_contract_event_activity","event_type_filter":{"contract_addresses":["0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48"]},"id":"675c980709b4be439a116ade","network_id":"ethereum-mainnet","notification_uri":"https://webhook.site/57cb34a7-51aa-4ba8-b0a5-b435bebf99a5","updated_at":"2024-12-16T21:47:29.07Z"}],"has_more":false}\n'
>>> wh1.delete_webhook()
CDP API REQUEST: DELETE https://api.cdp.coinbase.com/platform/v1/webhooks/675c980709b4be439a11 …
```

make delete a instance method

---

CHANGELOG.md
cdp/__init__.py
cdp/external_address.py

- Add `ExternalAddress` derived `Address` class to encapsulate external addresses.

chore: ExternalAddress derived Address class

---

CHANGELOG.md
README.md
cdp/client/__init__.py
cdp/client/api/external_addresses_api.py
cdp/client/models/__init__.py
cdp/client/models/broadcast_external_transfer_request.py
cdp/client/models/create_external_transfer_request.py
cdp/client/models/create_fund_operation_request.py
cdp/client/models/create_fund_quote_request.py
cdp/transfer.py
cdp/wallet.py
cdp/wallet_address.py
tests/test_transfer.py
tests/test_wallet.py
tests/test_wallet_address.py

Adds a skipBatching prop to createTransfer to allow devs to instruct transactions to be submitted immediately. This results in quicker submission times: ~2s round trip with skipped batching, vs ~20+.

feat(PSDK-782): allow users to send sponsored transactions immediately

---

.github/workflows/e2e_tests.yml
Makefile
poetry.lock
pyproject.toml
tests/conftest.py
tests/test_e2e.py

feat: e2e tests

---

tests/test_e2e.py

* removed faucet tests
* wrapping faucet calls in try/catch

fix: skip faucet e2e tests if limit reached

---

CHANGELOG.md
Makefile
cdp/wallet.py
tests/test_wallet.py

- Hot Fix `Wallet.import_wallet(...)` method to allow for specifying `network_id` optionally defaulting to `base-sepolia`
- Note: This is not a breaking change because the input arg is optional

chore: Fix Mnemonic Seed Wallet import Specify Network ID

---

CHANGELOG.md
cdp/client/__init__.py
cdp/client/api/smart_contracts_api.py
cdp/client/models/__init__.py
cdp/client/models/compile_smart_contract_request.py
cdp/client/models/compiled_smart_contract.py
cdp/client/models/network_identifier.py
cdp/client/models/smart_contract.py
cdp/client/models/smart_contract_options.py
cdp/smart_contract.py
cdp/wallet.py
cdp/wallet_address.py
tests/factories/compiled_smart_contract_factory.py
tests/test_e2e.py
tests/test_smart_contract.py
tests/test_transfer.py
tests/test_wallet.py
tests/test_wallet_address.py

- Added `deploy_contract` in wallet_address.py and wallet.py to support deploying an arbitrary contract using the compiler version, solidity input json, contract name of the class to be deployed, and constructor arguments
- Unit tests added
- E2E test succeeds

feat: Add support for deploying arbitrary contracts

---

.github/workflows/e2e_tests.yml
tests/test_e2e.py

* configuration changes for serial job execution
* pinning python 3.10
* test refinements
e2e tests are failing due to parallel execution using the same set of CDP API credentials, causing multiple transfers to execute concurrently raising nonce errors instead of waiting for the current transaction to complete.

feat: stabalize e2e test workflow

---

CHANGELOG.md
cdp/asset.py
tests/test_asset.py

There was a bug in the from_model function in asset.py. On the backend side, any asset id is checksummed before retrieving its details, and when it returns a response to the SDK, its asset id is also checksummed. When a user enters a non-checksummed address, they will get an error since those two asset ids are not equivalent.
This change will allow users to use non-checksummed addresses without getting erroneous errors in their workflow.
Before:
```
>>> wallet.balance('0x8309fbdf021edf768dc13195741940ba544dea98')
ValueError: Unsupported asset ID: 0x8309fbdf021edf768dc13195741940ba544dea98
```
Now:
```
>>> wallet.balance('0x8309fbdf021edf768dc13195741940ba544dea98')
Decimal('0')
```
This change should not be a breaking change for the SDK. The same logic of the check for asset ids exists, …

Bug fix for non-checksummed address

---

CHANGELOG.md
tests/test_e2e.py

A Gasless transfer test was added for E2E tests. This test improves coverage for the gasless transfer feature, by ensuring the SDK can make gasless transfers for USDC over Base Sepolia.
This change will impact the E2E tests, which currently run in our CI/CD pipeline for Github PRs. The wallet data that is used for transferring USDC over Base Sepolia will need to be funded in case in runs out of funds for the test to pass.

chore: added USDC gasless transfer e2e test

---

cdp/cdp.py
cdp/errors.py
tests/conftest.py
tests/factories/api_key_factory.py
tests/test_api_key_utils.py
tests/test_cdp.py

- Right now when a user forgets to call Coinbase.configure, they see an unclear error message because the apiClients aren't defined. This PR uses the proxy pattern in javascript to intercept getting the apiClients, and returns a clear message to the user.
Formatting/linting fixed a few unrelated test files so they can be ignored.
- Added a unit test to confirm error behavior when not initialized. Updated conftest for global test setup to mock the APIClients - this was needed for all existing tests to succeed with the new behavior.
- E2E testing, both with and without Coinbase.configure, have expected behavior.
Here's how it looks:
```
❯ python test_smart_wallet.py 
Traceback (most recent call last):
File "/Users/rohanagarwal/code/cdp-sdk-python/test_smart_wallet.py", line 68, in <module> …
```

Improve error message when SDK is used and not initialized

---

cdp/user_operation.py
tests/factories/api_key_factory.py
tests/test_api_key_utils.py
tests/test_user_operation.py

- @CarsonRoscoe discovered that doing userOperation.status == 'complete' doesn't work since it's an enum. This PR makes it possible to do a string comparison
- Added unit test that succeeds after these code changes
- Tested E2E to see that string comparison work

Update UserOperation status to support string comparison
